apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}
  tags:
    - terraform
    - aws
    - infrastructure
    - iac
  links:
    - url: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}
      title: Source repository
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  {%- if values.system %}
  system: ${{ values.system }}
  {%- endif %}
