apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app
  namespace: example
  annotations:
    # Bind this KSA to the Google ServiceAccount created in infra/main.tf
    # GSA email format: <example_gsa_id>@<project_id>.iam.gserviceaccount.com
    iam.gke.io/gcp-service-account: ${{ values.name }}-example@${{ values.gcpProject }}.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: example-app
    app.kubernetes.io/part-of: ${{ values.name }}
