site_name: ${{ values.name }}
site_description: ${{ values.description }}

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - content.code.copy
    - content.action.edit

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details

nav:
  - Overview: index.md
  - Development: development.md
