apiVersion: v1
kind: Service
metadata:
  name: example-app
  namespace: example
  labels:
    app.kubernetes.io/name: example-app
    app.kubernetes.io/part-of: ${{ values.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: example-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
