"""FastAPI application entry point for ${{ values.name }}.

Defines the FastAPI app, request/response models, and HTTP routes.
The OpenAPI 3.1 spec is auto-generated by FastAPI and served at
``/openapi.json``; Swagger UI lives at ``/docs`` and ReDoc at ``/redoc``.
"""

from __future__ import annotations

import logging
import os
import sys

import structlog
from fastapi import FastAPI
from pydantic import BaseModel, Field

from app import __version__


def _configure_logging() -> None:
    """Configure structlog to emit JSON in production, pretty output in dev."""
    log_level = os.getenv("LOG_LEVEL", "info").upper()
    logging.basicConfig(
        format="%(message)s",
        stream=sys.stdout,
        level=log_level,
    )

    is_tty = sys.stdout.isatty()
    renderer: structlog.types.Processor = (
        structlog.dev.ConsoleRenderer() if is_tty else structlog.processors.JSONRenderer()
    )

    structlog.configure(
        processors=[
            structlog.contextvars.merge_contextvars,
            structlog.processors.add_log_level,
            structlog.processors.TimeStamper(fmt="iso", utc=True),
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,
            renderer,
        ],
        wrapper_class=structlog.make_filtering_bound_logger(
            logging.getLevelName(log_level),
        ),
        cache_logger_on_first_use=True,
    )


_configure_logging()
logger = structlog.get_logger(__name__)


app = FastAPI(
    title="${{ values.name }}",
    description="${{ values.description }}",
    version=__version__,
    openapi_url="/openapi.json",
    docs_url="/docs",
    redoc_url="/redoc",
)


# --------------------------------------------------------------------------
# Models
# --------------------------------------------------------------------------


class HealthResponse(BaseModel):
    """Liveness probe payload."""

    status: str = Field(..., description="Always 'ok' when the service is up.")
    version: str = Field(..., description="Running service version (from app.__version__).")


class EchoRequest(BaseModel):
    """Request body for the demo echo endpoint."""

    message: str = Field(..., min_length=1, description="Arbitrary string to echo back.")


class EchoResponse(BaseModel):
    """Response body for the demo echo endpoint."""

    message: str = Field(..., description="The same string that was sent in.")


# --------------------------------------------------------------------------
# Routes
# --------------------------------------------------------------------------


@app.get(
    "/health",
    response_model=HealthResponse,
    tags=["system"],
    summary="Liveness probe",
)
async def health() -> HealthResponse:
    """Return a static OK + the running version. Used by orchestrators for liveness."""
    return HealthResponse(status="ok", version=__version__)


@app.post(
    "/echo",
    response_model=EchoResponse,
    tags=["demo"],
    summary="Echo the request body",
)
async def echo(req: EchoRequest) -> EchoResponse:
    """Echo the incoming message — useful for verifying routing and serialisation."""
    logger.info("echo_called", message_length=len(req.message))
    return EchoResponse(message=req.message)


# --------------------------------------------------------------------------
# Entry point (for `python -m app.main` or the console script)
# --------------------------------------------------------------------------


def run() -> None:
    """Console-script entry point. Boots uvicorn against this module's ``app``."""
    import uvicorn

    host = os.getenv("HOST", "0.0.0.0")  # noqa: S104 — service binds publicly by design
    port = int(os.getenv("PORT", "${{ values.listenPort }}"))
    log_level = os.getenv("LOG_LEVEL", "info").lower()

    logger.info("starting_${{ values.name | replace('-', '_') }}", host=host, port=port, version=__version__)
    uvicorn.run(
        "app.main:app",
        host=host,
        port=port,
        log_level=log_level,
        access_log=True,
    )


if __name__ == "__main__":
    run()
