apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    {{- include "baseline.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    {{- include "baseline.labels" . | nindent 4 }}
