site_name: ${{ values.name }}
site_description: ${{ values.description }}
docs_dir: docs
nav:
  - Overview: index.md
  - Development: development.md
plugins:
  - techdocs-core
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
